{{- if and .Values.database.createSecret .Values.database.url (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgram.fullname" . }}
  labels:
    {{- include "postgram.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.urlSecretKey }}: {{ .Values.database.url | quote }}
{{- end }}
