apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgram.fullname" . }}
  labels:
    {{- include "postgram.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "postgram.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
